### ISSUE TITLE
SIP Registration Failed : Error 407

### ISSUE THREAD

**Issue by aduggirala28** [RestComm/restcomm-web-sdk#108]
I have the SIP registration error while doing the tutorial at http://docs.telestax.com/restcomm-client-web-sdk-quick-start/ . I have given my own login credentials.The credentials are right as I am able to login with them at cloud.restcomm.com. I am trying to call from the a restcomm client to a SIP number linked to an app I designed using the RVD.  The hello world demo also produces the same errors.
Thank you.
Given below are the errors/logs in my browser console.

```
This appears to be Chrome
WebRTComm.js:4893 2017-10-07 12:23:40.264 INFO Device::setup(): {"debug":true,"username":"user_name","password":"**********"}
[Object.setup (https://localhost:7443/scripts/RestCommWebClient.js:853:13)]
WebRTComm.js:4893 2017-10-07 12:23:40.265 INFO Device::setup(): registrar has not been provided. Defaulting to wss://cloud.restcomm.com:5063
[Object.setup (https://localhost:7443/scripts/RestCommWebClient.js:866:13)]
WebRTComm.js:4893 2017-10-07 12:23:40.265 INFO Device::setup(): domain has not been provided. Defaulting to cloud.restcomm.com
[Object.setup (https://localhost:7443/scripts/RestCommWebClient.js:870:13)]
WebRTComm.js:4893 2017-10-07 12:23:40.266 INFO WrtcEventListener::WrtcEventListener constructor
[new WrtcEventListener (https://localhost:7443/scripts/RestCommWebClient.js:75:11)]
WebRTComm.js:4893 2017-10-07 12:23:40.277 INFO Device::ready(), assigning ready callback
[Object.ready (https://localhost:7443/scripts/RestCommWebClient.js:926:13)]
WebRTComm.js:4893 2017-10-07 12:23:40.278 INFO Device::error(), assigning error callback
[Object.error (https://localhost:7443/scripts/RestCommWebClient.js:1008:13)]
WebRTComm.js:4893 2017-10-07 12:23:40.278 INFO Device::connect(), assigning connect callback
[Object.connect (https://localhost:7443/scripts/RestCommWebClient.js:1032:14)]
WebRTComm.js:4893 2017-10-07 12:23:40.310 INFO This appears to be Chrome
[Object.log (https://localhost:7443/scripts/adapter.js:54:17)]
WebRTComm.js:4893 2017-10-07 12:23:40.398 INFO 2017-10-07 12:23:40.398 INFO WSMessageChannel:createWebSocket(): the websocket is opened
[WebSocket.websocket.onopen (https://localhost:7443/scripts/jain-sip.js:25460:17)]
[commonLog (https://localhost:7443/scripts/WebRTComm.js:4893:9)]
WebRTComm.js:4893 2017-10-07 12:23:40.438 INFO 2017-10-07 12:23:40.438 INFO SIP message sent: REGISTER sip:cloud.restcomm.com SIP/2.0
Call-ID: 1499703820401
CSeq: 1 REGISTER
From: sip:user_name@cloud.restcomm.com;tag=1499703820423
To: sip:user_name@cloud.restcomm.com
Via: SIP/2.0/WSS nnFF3TVu2mgw.invalid;branch=z9hG4bK-393130-721d064a7539735f3ec53a687c8e14c8;rport
Max-Forwards: 70
User-Agent: TelScale RestComm Web Client 1.0.0 BETA4
Expires: 3600
Allow: INVITE,ACK,CANCEL,BYE,OPTIONS,MESSAGE
Contact: <sip:user_name@nnFF3TVu2mgw.invalid;[object Object]>
Content-Length: 0

[WSMessageChannel.sendMessage (https://localhost:7443/scripts/jain-sip.js:25514:13)]  
[commonLog (https://localhost:7443/scripts/WebRTComm.js:4893:9)] 
WebRTComm.js:4893 2017-10-07 12:23:40.478 INFO 2017-10-07 12:23:40.478 INFO SIP message received: SIP/2.0 407 Proxy Authentication required
To: sip:user_name@cloud.restcomm.com;tag=14982618_8fc6f305_57a5b08a_1f77a809
Via: SIP/2.0/WSS 174.79.191.55:31055;branch=z9hG4bK-393130-721d064a7539735f3ec53a687c8e14c8;rport=31055;received=174.79.191.55
CSeq: 1 REGISTER
Call-ID: 1499703820401
From: sip:user_name@cloud.restcomm.com;tag=1499703820423
Server: Restcomm 8.2.0.1549
Proxy-Authenticate: Digest realm="cloud.restcomm.com",nonce="38386136363834632d383833612d343"
Content-Length: 0

[WSMsgParser.parsermessage (https://localhost:7443/scripts/jain-sip.js:20482:13)]  
[commonLog (https://localhost:7443/scripts/WebRTComm.js:4893:9)] 
WebRTComm.js:4893 2017-10-07 12:23:40.491 INFO 2017-10-07 12:23:40.491 INFO SIP message sent: REGISTER sip:cloud.restcomm.com SIP/2.0
CSeq: 2 REGISTER
User-Agent: TelScale RestComm Web Client 1.0.0 BETA4
Expires: 3600
Allow: INVITE,ACK,CANCEL,BYE,OPTIONS,MESSAGE
Contact: <sip:user_name@nnFF3TVu2mgw.invalid;[object Object]>
Call-ID: 1499703820401
Via: SIP/2.0/WSS nnFF3TVu2mgw.invalid;branch=z9hG4bK-393130-19b09e6e948c8fd482b003af3815f009;rport
From: sip:manas.sampat@cloud.restcomm.com;tag=1499703820423
To: sip:manas.sampat@cloud.restcomm.com
Max-Forwards: 70
Proxy-Authorization: Digest username="user_name",realm="cloud.restcomm.com",nonce="38386136363834632d383833612d343",response="e5ea997168f2501d8846461ff29f3826",uri="sip:cloud.restcomm.com",algorithm=MD5
Content-Length: 0

[WSMessageChannel.sendMessage (https://localhost:7443/scripts/jain-sip.js:25514:13)]  
[commonLog (https://localhost:7443/scripts/WebRTComm.js:4893:9)] 
WebRTComm.js:4893 2017-10-07 12:23:48.486 INFO 2017-10-07 12:23:48.486 INFO SIPTransactionStack.prototype.removeDialog(): id=1499703820401:1499703820423:14982618_8fc6f305_57a5b08a_1f77a809
[SipStackImpl.SIPTransactionStack.removeDialog (https://localhost:7443/scripts/jain-sip.js:24198:13)]
[commonLog (https://localhost:7443/scripts/WebRTComm.js:4893:9)]
WebRTComm.js:4893 2017-10-07 12:24:12.498 ERROR 2017-10-07 12:24:12.498 ERROR PrivateJainSipClientConnector:processTimeout(): SIP registration timed out, no response from SIP server, Call-Id: 1499703820401. Retrying...

Stack trace:
at commonLog (https://localhost:7443/scripts/WebRTComm.js:4852:10)
at Object.console.error (https://localhost:7443/scripts/WebRTComm.js:4925:4)
at PrivateJainSipClientConnector.processTimeout (https://localhost:7443/scripts/WebRTComm.js:1701:12)
at EventScanner.deliverEvent (https://localhost:7443/scripts/jain-sip.js:29678:25)
at SipProviderImpl.handleEvent (https://localhost:7443/scripts/jain-sip.js:30896:27)
at SipProviderImpl.transactionErrorEvent (https://localhost:7443/scripts/jain-sip.js:31439:14)
at SIPClientTransaction.SIPTransaction.raiseErrorEvent (https://localhost:7443/scripts/jain-sip.js:27602:22)
at SIPClientTransaction.fireTimeoutTimer (https://localhost:7443/scripts/jain-sip.js:28302:14)
at SIPClientTransaction.SIPTransaction.fireTimer (https://localhost:7443/scripts/jain-sip.js:27522:18)
at https://localhost:7443/scripts/jain-sip.js:28481:26

Stack trace:
at commonLog (https://localhost:7443/scripts/WebRTComm.js:4852:10)
at console.error (https://localhost:7443/scripts/WebRTComm.js:4925:4)
at commonLog (https://localhost:7443/scripts/WebRTComm.js:4893:9)
at Object.console.error (https://localhost:7443/scripts/WebRTComm.js:4925:4)
at PrivateJainSipClientConnector.processTimeout (https://localhost:7443/scripts/WebRTComm.js:1701:12)
at EventScanner.deliverEvent (https://localhost:7443/scripts/jain-sip.js:29678:25)
at SipProviderImpl.handleEvent (https://localhost:7443/scripts/jain-sip.js:30896:27)
at SipProviderImpl.transactionErrorEvent (https://localhost:7443/scripts/jain-sip.js:31439:14)
at SIPClientTransaction.SIPTransaction.raiseErrorEvent (https://localhost:7443/scripts/jain-sip.js:27602:22)
at SIPClientTransaction.fireTimeoutTimer (https://localhost:7443/scripts/jain-sip.js:28302:14)
commonLog @ WebRTComm.js:4893
console.error @ WebRTComm.js:4925
commonLog @ WebRTComm.js:4893
console.error @ WebRTComm.js:4925
PrivateJainSipClientConnector.processTimeout @ WebRTComm.js:1701
EventScanner.deliverEvent @ jain-sip.js:29678
SipProviderImpl.handleEvent @ jain-sip.js:30896
SipProviderImpl.transactionErrorEvent @ jain-sip.js:31439
SIPTransaction.raiseErrorEvent @ jain-sip.js:27602
SIPClientTransaction.fireTimeoutTimer @ jain-sip.js:28302
SIPTransaction.fireTimer @ jain-sip.js:27522
(anonymous) @ jain-sip.js:28481
WebRTComm.js:4893 2017-10-07 12:24:12.516 INFO 2017-10-07 12:24:12.514 INFO SIP message sent: REGISTER sip:cloud.restcomm.com SIP/2.0
Call-ID: 1499703852503
CSeq: 1 REGISTER
From: sip:user_name@cloud.restcomm.com;tag=1499703852507
To: sip:user_name@cloud.restcomm.com
Via: SIP/2.0/WSS nnFF3TVu2mgw.invalid;branch=z9hG4bK-393130-5273da645ef3d648b9d47e98cf45b6a0;rport
Max-Forwards: 70
User-Agent: TelScale RestComm Web Client 1.0.0 BETA4
Expires: 3600
Allow: INVITE,ACK,CANCEL,BYE,OPTIONS,MESSAGE
Contact: <sip:user_name@nnFF3TVu2mgw.invalid;[object Object]>
Content-Length: 0

[WSMessageChannel.sendMessage (https://localhost:7443/scripts/jain-sip.js:25514:13)]  
[commonLog (https://localhost:7443/scripts/WebRTComm.js:4893:9)] 
WebRTComm.js:4893 2017-10-07 12:24:12.525 WARN 2017-10-07 12:24:12.523 WARN WebRTCommClient:onPrivateClientConnectorOpenWarningEvent()⚠️Register Request Timeout
[WebRTCommClient.onPrivateClientConnectorOpenWarningEvent (https://localhost:7443/scripts/WebRTComm.js:4764:10)]
[commonLog (https://localhost:7443/scripts/WebRTComm.js:4893:9)]
commonLog @ WebRTComm.js:4893
console.warn @ WebRTComm.js:4919
commonLog @ WebRTComm.js:4893
console.warn @ WebRTComm.js:4919
WebRTCommClient.onPrivateClientConnectorOpenWarningEvent @ WebRTComm.js:4764
PrivateJainSipClientConnector.processTimeout @ WebRTComm.js:1705
EventScanner.deliverEvent @ jain-sip.js:29678
SipProviderImpl.handleEvent @ jain-sip.js:30896
SipProviderImpl.transactionErrorEvent @ jain-sip.js:31439
SIPTransaction.raiseErrorEvent @ jain-sip.js:27602
SIPClientTransaction.fireTimeoutTimer @ jain-sip.js:28302
SIPTransaction.fireTimer @ jain-sip.js:27522
(anonymous) @ jain-sip.js:28481
WebRTComm.js:4893 2017-10-07 12:24:12.570 INFO 2017-10-07 12:24:12.570 INFO SIP message received: SIP/2.0 407 Proxy Authentication required
To: sip:user_name@cloud.restcomm.com;tag=05979129_8fc6f305_57a5b08a_e62276e2
Via: SIP/2.0/WSS 174.79.191.55:31055;branch=z9hG4bK-393130-5273da645ef3d648b9d47e98cf45b6a0;rport=31055;received=174.79.191.55
CSeq: 1 REGISTER
Call-ID: 1499703852503
From: sip:user_name@cloud.restcomm.com;tag=1499703852507
Server: Restcomm 8.2.0.1549
Proxy-Authenticate: Digest realm="cloud.restcomm.com",nonce="38386538303338322d323333612d343"
Content-Length: 0

[WSMsgParser.parsermessage (https://localhost:7443/scripts/jain-sip.js:20482:13)]  
[commonLog (https://localhost:7443/scripts/WebRTComm.js:4893:9)] 
WebRTComm.js:4893 2017-10-07 12:24:12.577 ERROR 2017-10-07 12:24:12.577 ERROR PrivateJainSipClientConnector:processSipRegisterResponse(): SIP registration failed:407 [object Object]

Stack trace:
at commonLog (https://localhost:7443/scripts/WebRTComm.js:4852:10)
at Object.console.error (https://localhost:7443/scripts/WebRTComm.js:4925:4)
at PrivateJainSipClientConnector.processSipRegisterResponse (https://localhost:7443/scripts/WebRTComm.js:1820:12)
at PrivateJainSipClientConnector.processResponse (https://localhost:7443/scripts/WebRTComm.js:1645:9)
at EventScanner.deliverEvent (https://localhost:7443/scripts/jain-sip.js:29660:25)
at SipProviderImpl.handleEvent (https://localhost:7443/scripts/jain-sip.js:30896:27)
at DialogFilter.processResponseargu3 (https://localhost:7443/scripts/jain-sip.js:30388:17)
at DialogFilter.processResponse (https://localhost:7443/scripts/jain-sip.js:30246:14)
at SIPClientTransaction.nonInviteClientTransaction (https://localhost:7443/scripts/jain-sip.js:28113:32)
at SIPClientTransaction.processResponseargu3 (https://localhost:7443/scripts/jain-sip.js:28083:18)

Stack trace:
at commonLog (https://localhost:7443/scripts/WebRTComm.js:4852:10)
at console.error (https://localhost:7443/scripts/WebRTComm.js:4925:4)
at commonLog (https://localhost:7443/scripts/WebRTComm.js:4893:9)
at Object.console.error (https://localhost:7443/scripts/WebRTComm.js:4925:4)
at PrivateJainSipClientConnector.processSipRegisterResponse (https://localhost:7443/scripts/WebRTComm.js:1820:12)
at PrivateJainSipClientConnector.processResponse (https://localhost:7443/scripts/WebRTComm.js:1645:9)
at EventScanner.deliverEvent (https://localhost:7443/scripts/jain-sip.js:29660:25)
at SipProviderImpl.handleEvent (https://localhost:7443/scripts/jain-sip.js:30896:27)
at DialogFilter.processResponseargu3 (https://localhost:7443/scripts/jain-sip.js:30388:17)
at DialogFilter.processResponse (https://localhost:7443/scripts/jain-sip.js:30246:14)
commonLog @ WebRTComm.js:4893
console.error @ WebRTComm.js:4925
commonLog @ WebRTComm.js:4893
console.error @ WebRTComm.js:4925
PrivateJainSipClientConnector.processSipRegisterResponse @ WebRTComm.js:1820
PrivateJainSipClientConnector.processResponse @ WebRTComm.js:1645
EventScanner.deliverEvent @ jain-sip.js:29660
SipProviderImpl.handleEvent @ jain-sip.js:30896
DialogFilter.processResponseargu3 @ jain-sip.js:30388
DialogFilter.processResponse @ jain-sip.js:30246
SIPClientTransaction.nonInviteClientTransaction @ jain-sip.js:28113
SIPClientTransaction.processResponseargu3 @ jain-sip.js:28083
SIPClientTransaction.processResponse @ jain-sip.js:28006
SIPClientTransaction.processResponseargu2 @ jain-sip.js:28062
SIPClientTransaction.processResponse @ jain-sip.js:27999
WSMsgParser.processMessage @ jain-sip.js:20515
WSMsgParser.parsermessage @ jain-sip.js:20483
websocket.onmessage @ jain-sip.js:25479
WebRTComm.js:4893 2017-10-07 12:24:12.580 ERROR 2017-10-07 12:24:12.580 ERROR WebRTCommClient:onPrivateClientConnectorOpenErrorEvent():error:undefined

Stack trace:
at commonLog (https://localhost:7443/scripts/WebRTComm.js:4852:10)
at Object.console.error (https://localhost:7443/scripts/WebRTComm.js:4925:4)
at WebRTCommClient.onPrivateClientConnectorOpenErrorEvent (https://localhost:7443/scripts/WebRTComm.js:4740:10)
at PrivateJainSipClientConnector.processSipRegisterResponse (https://localhost:7443/scripts/WebRTComm.js:1822:25)
at PrivateJainSipClientConnector.processResponse (https://localhost:7443/scripts/WebRTComm.js:1645:9)
at EventScanner.deliverEvent (https://localhost:7443/scripts/jain-sip.js:29660:25)
at SipProviderImpl.handleEvent (https://localhost:7443/scripts/jain-sip.js:30896:27)
at DialogFilter.processResponseargu3 (https://localhost:7443/scripts/jain-sip.js:30388:17)
at DialogFilter.processResponse (https://localhost:7443/scripts/jain-sip.js:30246:14)
at SIPClientTransaction.nonInviteClientTransaction (https://localhost:7443/scripts/jain-sip.js:28113:32)

Stack trace:
at commonLog (https://localhost:7443/scripts/WebRTComm.js:4852:10)
at console.error (https://localhost:7443/scripts/WebRTComm.js:4925:4)
at commonLog (https://localhost:7443/scripts/WebRTComm.js:4893:9)
at Object.console.error (https://localhost:7443/scripts/WebRTComm.js:4925:4)
at WebRTCommClient.onPrivateClientConnectorOpenErrorEvent (https://localhost:7443/scripts/WebRTComm.js:4740:10)
at PrivateJainSipClientConnector.processSipRegisterResponse (https://localhost:7443/scripts/WebRTComm.js:1822:25)
at PrivateJainSipClientConnector.processResponse (https://localhost:7443/scripts/WebRTComm.js:1645:9)
at EventScanner.deliverEvent (https://localhost:7443/scripts/jain-sip.js:29660:25)
at SipProviderImpl.handleEvent (https://localhost:7443/scripts/jain-sip.js:30896:27)
at DialogFilter.processResponseargu3 (https://localhost:7443/scripts/jain-sip.js:30388:17)
commonLog @ WebRTComm.js:4893
console.error @ WebRTComm.js:4925
commonLog @ WebRTComm.js:4893
console.error @ WebRTComm.js:4925
WebRTCommClient.onPrivateClientConnectorOpenErrorEvent @ WebRTComm.js:4740
PrivateJainSipClientConnector.processSipRegisterResponse @ WebRTComm.js:1822
PrivateJainSipClientConnector.processResponse @ WebRTComm.js:1645
EventScanner.deliverEvent @ jain-sip.js:29660
SipProviderImpl.handleEvent @ jain-sip.js:30896
DialogFilter.processResponseargu3 @ jain-sip.js:30388
DialogFilter.processResponse @ jain-sip.js:30246
SIPClientTransaction.nonInviteClientTransaction @ jain-sip.js:28113
SIPClientTransaction.processResponseargu3 @ jain-sip.js:28083
SIPClientTransaction.processResponse @ jain-sip.js:28006
SIPClientTransaction.processResponseargu2 @ jain-sip.js:28062
SIPClientTransaction.processResponse @ jain-sip.js:27999
WSMsgParser.processMessage @ jain-sip.js:20515
WSMsgParser.parsermessage @ jain-sip.js:20483
websocket.onmessage @ jain-sip.js:25479
WebRTComm.js:4893 2017-10-07 12:24:12.585 INFO 2017-10-07 12:24:12.585 INFO WrtcEventListener::onWebRTCommClientOpenErrorEventundefined
[WrtcEventListener.onWebRTCommClientOpenErrorEvent (https://localhost:7443/scripts/RestCommWebClient.js:98:13)]
[commonLog (https://localhost:7443/scripts/WebRTComm.js:4893:9)]
WebRTComm.js:4893 2017-10-07 12:24:20.494 INFO 2017-10-07 12:24:20.494 INFO SIPTransactionStack.prototype.removeDialog(): id=null
[SipStackImpl.SIPTransactionStack.removeDialog (https://localhost:7443/scripts/jain-sip.js:24198:13)]
[commonLog (https://localhost:7443/scripts/WebRTComm.js:4893:9)]
WebRTComm.js:4893 2017-10-07 12:24:20.576 INFO 2017-10-07 12:24:20.576 INFO SIPTransactionStack.prototype.removeDialog(): id=1499703852503:1499703852507:05979129_8fc6f305_57a5b08a_e62276e2
[SipStackImpl.SIPTransactionStack.removeDialog (https://localhost:7443/scripts/jain-sip.js:24198:13)]
[commonLog (https://localhost:7443/scripts/WebRTComm.js:4893:9)] 
```

**Comment by atsakiridis** [comment]
@aduggirala28 registration indeed fails, but doesn't seem to be because of wrong credentials; instead it seems to timeout somehow. But how do you know that the credentials are right? Do you have an account in cloud.restcomm.com? If so have you checked if there is a client called `user_name` (or whatever you use to REGISTER from restcomm-web-sdk)

**Comment by aduggirala28** [comment]
Yes, I do have an account on cloud.restcomm.com. Yes the caller is a client on cloud.restcomm and the callee is number linked with an RVD app.

**Comment by atsakiridis** [comment]
@aduggirala28 if you are using the sample code, can you try it without registration, like we illustrate [here](http://documentation.telestax.com/connect/sdks/restcomm-client-web-sdk-quick-start.html) and call for example +1235@cloud.restcomm.com. Does that work?

**Comment by pouraghajanOldAcc** [comment]
I'm facing the same issue after changing restcomm to use SSL instead of plain HTTP.
btw, I'm using CentOS 7, Restcomm-JBoss-AS7-8.7.1.25, a self signed certificate (instructed [here](https://www.restcomm.com/docs/connect/configuration/Restcomm%20-%20Enable%20HTTPS%20secure%20connector%20on%20JBoss%20AS%207%20or%20EAP%206.html)) and I have defined my hostname in restcomm.conf as well.

Here are my browser logs : 

```
2018-02-09 20:46:01.258 ERROR PrivateJainSipClientConnector:processSipRegisterResponse(): SIP registration failed:403  [object Object] 

Stack trace: 
    at commonLog (https://192.168.x.x:8443/olympus/resources/assets/WebRTComm.63fcb1db625e783e.js:4950:10)
    at console.error (https://192.168.x.x:8443/olympus/resources/assets/WebRTComm.63fcb1db625e783e.js:5023:4)
    at PrivateJainSipClientConnector.processSipRegisterResponse (https://192.168.x.x:8443/olympus/resources/assets/WebRTComm.63fcb1db625e783e.js:1821:12)
    at PrivateJainSipClientConnector.processResponse (https://192.168.x.x:8443/olympus/resources/assets/WebRTComm.63fcb1db625e783e.js:1646:9)
    at EventScanner.deliverEvent (https://192.168.x.x:8443/olympus/resources/assets/jain-sip.cb5c2df41b743fd3.js:29648:25)
    at SipProviderImpl.handleEvent (https://192.168.x.x:8443/olympus/resources/assets/jain-sip.cb5c2df41b743fd3.js:30884:27)
    at DialogFilter.processResponseargu3 (https://192.168.x.x:8443/olympus/resources/assets/jain-sip.cb5c2df41b743fd3.js:30376:17)
    at DialogFilter.processResponse (https://192.168.x.x:8443/olympus/resources/assets/jain-sip.cb5c2df41b743fd3.js:30234:14)
    at SIPClientTransaction.nonInviteClientTransaction (https://192.168.x.x:8443/olympus/resources/assets/jain-sip.cb5c2df41b743fd3.js:28101:32)
    at SIPClientTransaction.processResponseargu3 (https://192.168.x.x:8443/olympus/resources/assets/jain-sip.cb5c2df41b743fd3.js:28071:18)
commonLog @ WebRTComm.63fcb1db625e783e.js:4991
WebRTComm.63fcb1db625e783e.js:4991 2018-02-09 20:46:01.258 ERROR WebRTCommClient:onPrivateClientConnectorOpenErrorEvent():error:undefined 

Stack trace: 
    at commonLog (https://192.168.x.x:8443/olympus/resources/assets/WebRTComm.63fcb1db625e783e.js:4950:10)
    at console.error (https://192.168.x.x:8443/olympus/resources/assets/WebRTComm.63fcb1db625e783e.js:5023:4)
    at WebRTCommClient.onPrivateClientConnectorOpenErrorEvent (https://192.168.x.x:8443/olympus/resources/assets/WebRTComm.63fcb1db625e783e.js:4819:10)
    at PrivateJainSipClientConnector.processSipRegisterResponse (https://192.168.x.x:8443/olympus/resources/assets/WebRTComm.63fcb1db625e783e.js:1823:25)
    at PrivateJainSipClientConnector.processResponse (https://192.168.x.x:8443/olympus/resources/assets/WebRTComm.63fcb1db625e783e.js:1646:9)
    at EventScanner.deliverEvent (https://192.168.x.x:8443/olympus/resources/assets/jain-sip.cb5c2df41b743fd3.js:29648:25)
    at SipProviderImpl.handleEvent (https://192.168.x.x:8443/olympus/resources/assets/jain-sip.cb5c2df41b743fd3.js:30884:27)
    at DialogFilter.processResponseargu3 (https://192.168.x.x:8443/olympus/resources/assets/jain-sip.cb5c2df41b743fd3.js:30376:17)
    at DialogFilter.processResponse (https://192.168.x.x:8443/olympus/resources/assets/jain-sip.cb5c2df41b743fd3.js:30234:14)
    at SIPClientTransaction.nonInviteClientTransaction (https://192.168.x:8443/olympus/resources/assets/jain-sip.cb5c2df41b743fd3.js:28101:32)
```
@atsakiridis

**Comment by pouraghajanOldAcc** [comment]
I think it could be useful if I add some server side DEBUG level logs as well, clearing out my issue : 

```
06:24:34,351 DEBUG [gov.nist.javax.sip.stack.NioTcpMessageProcessor] (RestComm-akka.actor.default-dispatcher-39) Connected. lets set WRITE ops.
06:24:34,352 DEBUG [org.mobicents.servlet.sip.message.TransactionApplicationData] (MSS-Executor-Thread-3) cleaning up the application data org.mobicents.servlet.sip.message.TransactionApplicationData@9b15c3f
06:24:34,352 DEBUG [gov.nist.javax.sip.stack.NioTcpMessageProcessor] (RestComm-akka.actor.default-dispatcher-39) Waking up selector thread
06:24:34,352 DEBUG [org.mobicents.servlet.sip.core.session.SipSessionImpl] (MSS-Executor-Thread-3) cleanDialogInformation null
06:24:34,352 DEBUG [org.mobicents.servlet.sip.core.session.SipSessionImpl] (MSS-Executor-Thread-3) cleanDialogInformation terminate false
06:24:34,352 DEBUG [gov.nist.javax.sip.stack.NioTcpMessageProcessor] (NioSelector-WSS-192.168.x.x/5083) null selectedKeys
06:24:34,352 DEBUG [org.mobicents.servlet.sip.core.session.SipApplicationSessionImpl] (MSS-Executor-Thread-3) Before Semaphore released for sipApplicationSession=4d01c13b;RestComm semaphore=java.util.concurrent.Semaphore@5b1f3111[Permits = 0]
06:24:34,352 INFO  [gov.nist.javax.sip.stack.SIPTransactionStack] (RestComm-akka.actor.default-dispatcher-39) <message
from="192.168.x.x:5083"
to="192.168.x.y:1860"
time="1536067474350"
isSender="true"
transactionId="z9hg4bk-393132-3f05db1d3a873c992e25d956a255e45c"
callId="1536067474225"
firstLine="SIP/2.0 403 Forbidden"
>
<![CDATA[SIP/2.0 403 Forbidden
To: <sip:myuser@192.168.x.x>;tag=84305530_3d67b3b4_57a5b08a_4d01c13b
Via: SIP/2.0/WSS 192.168.x.y:1860;branch=z9hG4bK-393132-3f05db1d3a873c992e25d956a255e45c;rport=1860;received=192.168.x.y
CSeq: 2 REGISTER
Call-ID: 1536067474225
From: <sip:myuser@192.168.x.x>;tag=1536067474226
Server: Restcomm 8.4.0-227
Content-Length: 0

]]>
</message>
```

**Comment by pouraghajanOldAcc** [comment]
A bizarre resolution for my problem:
Guys, after changing the RestComm connectivity mode to SSL, strangely you need to delete all the clients you had defined in the system before and recreate them again (Changing client's password doesn't suffice here, you need to explicitly delete the client).
A bit disappointed of RestComm team neither mentioned this in any doc nor fixed the problem in the code (It literally took 48 hours of my time, going back and force among docs and forums). but thanks anyways for a great free communication platform.

**Comment by armachea** [comment]
Hi Majid,

I have the same error on registration am receiving 403 and am not using SSL. can you please let me know what am doing wrong 👍 

this is my configuration:

	>>>>>> Restcomm.conf  <<<<<<<
	
# Network configuration
NET_INTERFACE='ens160'
PRIVATE_IP='192.168.153.174'
SUBNET_MASK='255.255.255.0'
NETWORK='192.168.153.1' 
BROADCAST_ADDRESS='182.168.153.255'
# PUBLIC IP ADDRESS
STATIC_ADDRESS=''
#hostname of the server to be used at restcomm.xml. If not set the STATIC_ADDRESS will be used.
RESTCOMM_HOSTNAME='OldUbuntu'

>>>>>> advanced.conf  <<<<<<<

#Secure SSL configuration.
#Allowed values FALSE, SELF, AUTH.
#If SELF set self-signed certificate will be created.
#If AUTH, Authorized certificate will be used.Need to place the certificate at "$RESTCOMM_HOME/standalone/configuration/"
#To Disable use 'FALSE'
SECURESSL=FALSE
TRUSTSTORE_FILE='inmokey.jks' #File should be located at $RESTCOMM_HOME/standalone/configuration folder. Provide just the name of the trustore file.
TRUSTSTORE_PASSWORD='password' #Password for the trustore file
TRUSTSTORE_ALIAS='inmo' #The certificate alias
#comma separated protocols to set on SSLEngine, if empty use stack defaults
SSL_PROTOCOLS=''
#comma separated cipher suites to set on SSLEngine, if empty use stack defaults
SSL_CIPHER_SUITES=''

#HTTPS Settings
DISABLE_HTTP='true' #Control HTTP connector behavior. Values, TRUE=HTTP connector will be disable, FALSE=HTTP Connector will be active, REDIRECT= http -> https redirection will be enabled (For CLI RestAPI requests when redirect is active https needs to be used).
#Control whether or not Restcomm will accept self-signed certificates.
SSL_MODE='allowall' #Values allowall=allow self-signed certificates, strict=don't allow self signed certificates. If SECURESSL=SELF set to "allowall" automaticaly.
 

Am using hostname as you can see but when i wanna register my client i do it this way:

99199:192.168.153.174:5060   UDP/TCP

i tried with hostname but no luck

99199:OldUbuntu:5060   UDP/TCP

Br
