### ISSUE TITLE
Restcomm web sdk 

### ISSUE THREAD

**Issue by BabarAli78** [RestComm/restcomm-web-sdk#110]
Hi All,

I am implementing Restcomm Web-sdk to enable client communication but i am getting some errors. 

ERROR # 1

2018-17-04 15:07:11.284 ERROR PrivateJainSipClientConnector:processSipRegisterResponse(): SIP registration failed:403  [object Object] 

Stack trace: 
    at commonLog (file:///C:/Users/Babar%20Ali/Documents/GitHub/restcomm-web-sdk/samples/hello-world/scripts/WebRTComm.js:4852:10)
    at console.error (file:///C:/Users/Babar%20Ali/Documents/GitHub/restcomm-web-sdk/samples/hello-world/scripts/WebRTComm.js:4925:4)
    at PrivateJainSipClientConnector.processSipRegisterResponse (file:///C:/Users/Babar%20Ali/Documents/GitHub/restcomm-web-sdk/samples/hello-world/scripts/WebRTComm.js:1820:12)
    at PrivateJainSipClientConnector.processResponse (file:///C:/Users/Babar%20Ali/Documents/GitHub/restcomm-web-sdk/samples/hello-world/scripts/WebRTComm.js:1645:9)
    at EventScanner.deliverEvent (file:///C:/Users/Babar%20Ali/Documents/GitHub/restcomm-web-sdk/samples/hello-world/scripts/jain-sip.js:29660:25)
    at SipProviderImpl.handleEvent (file:///C:/Users/Babar%20Ali/Documents/GitHub/restcomm-web-sdk/samples/hello-world/scripts/jain-sip.js:30896:27)
    at DialogFilter.processResponseargu3 (file:///C:/Users/Babar%20Ali/Documents/GitHub/restcomm-web-sdk/samples/hello-world/scripts/jain-sip.js:30388:17)
    at DialogFilter.processResponse (file:///C:/Users/Babar%20Ali/Documents/GitHub/restcomm-web-sdk/samples/hello-world/scripts/jain-sip.js:30246:14)
    at SIPClientTransaction.nonInviteClientTransaction (file:///C:/Users/Babar%20Ali/Documents/GitHub/restcomm-web-sdk/samples/hello-world/scripts/jain-sip.js:28113:32)
    at SIPClientTransaction.processResponseargu3 (file:///C:/Users/Babar%20Ali/Documents/GitHub/restcomm-web-sdk/samples/hello-world/scripts/jain-sip.js:28083:18)
commonLog @ WebRTComm.js:4893
console.error @ WebRTComm.js:4925
PrivateJainSipClientConnector.processSipRegisterResponse @ WebRTComm.js:1820
PrivateJainSipClientConnector.processResponse @ WebRTComm.js:1645
EventScanner.deliverEvent @ jain-sip.js:29660
SipProviderImpl.handleEvent @ jain-sip.js:30896
DialogFilter.processResponseargu3 @ jain-sip.js:30388
DialogFilter.processResponse @ jain-sip.js:30246
SIPClientTransaction.nonInviteClientTransaction @ jain-sip.js:28113
SIPClientTransaction.processResponseargu3 @ jain-sip.js:28083
SIPClientTransaction.processResponse @ jain-sip.js:28006
SIPClientTransaction.processResponseargu2 @ jain-sip.js:28062
SIPClientTransaction.processResponse @ jain-sip.js:27999
WSMsgParser.processMessage @ jain-sip.js:20515
WSMsgParser.parsermessage @ jain-sip.js:20483
websocket.onmessage @ jain-sip.js:25479
WebRTComm.js:4893 

                   -------------------------------------------------------------------------------------------
**ERROR # 2** 

2018-17-04 15:07:11.290 ERROR WebRTCommClient:onPrivateClientConnectorOpenErrorEvent():error:undefined 

Stack trace: 
    at commonLog (file:///C:/Users/Babar%20Ali/Documents/GitHub/restcomm-web-sdk/samples/hello-world/scripts/WebRTComm.js:4852:10)
    at console.error (file:///C:/Users/Babar%20Ali/Documents/GitHub/restcomm-web-sdk/samples/hello-world/scripts/WebRTComm.js:4925:4)
    at WebRTCommClient.onPrivateClientConnectorOpenErrorEvent (file:///C:/Users/Babar%20Ali/Documents/GitHub/restcomm-web-sdk/samples/hello-world/scripts/WebRTComm.js:4740:10)
    at PrivateJainSipClientConnector.processSipRegisterResponse (file:///C:/Users/Babar%20Ali/Documents/GitHub/restcomm-web-sdk/samples/hello-world/scripts/WebRTComm.js:1822:25)
    at PrivateJainSipClientConnector.processResponse (file:///C:/Users/Babar%20Ali/Documents/GitHub/restcomm-web-sdk/samples/hello-world/scripts/WebRTComm.js:1645:9)
    at EventScanner.deliverEvent (file:///C:/Users/Babar%20Ali/Documents/GitHub/restcomm-web-sdk/samples/hello-world/scripts/jain-sip.js:29660:25)
    at SipProviderImpl.handleEvent (file:///C:/Users/Babar%20Ali/Documents/GitHub/restcomm-web-sdk/samples/hello-world/scripts/jain-sip.js:30896:27)
    at DialogFilter.processResponseargu3 (file:///C:/Users/Babar%20Ali/Documents/GitHub/restcomm-web-sdk/samples/hello-world/scripts/jain-sip.js:30388:17)
    at DialogFilter.processResponse (file:///C:/Users/Babar%20Ali/Documents/GitHub/restcomm-web-sdk/samples/hello-world/scripts/jain-sip.js:30246:14)
    at SIPClientTransaction.nonInviteClientTransaction (file:///C:/Users/Babar%20Ali/Documents/GitHub/restcomm-web-sdk/samples/hello-world/scripts/jain-sip.js:28113:32) 

Appreciate your kind support .

**Comment by gsaslis** [comment]
@BabarAli78 `403` is the `Forbidden` error code which probably means there's something wrong with the auth process. 

I'd start with checking that: 
* the client account exists. It is important to check it exists under the specific [organization](https://www.restcomm.com/docs/connect/api/organization-api.html#organization) you are trying to log into. 
* that the `Domain` you are specifying matches the one in the above organization.

Hope that helps...

**Comment by BabarAli78** [comment]
Hi @gsaslis  i have succeeded in doing client ready. yes you are right my credentials are wrong thats why it is giving 403 error.

Now after i click call button, the call goes to the other sip client which is logged in on another computer( on Olympus)  but at my end it is only ringing if the other party accept or reject there is no state change at my end. no connection establishment. Can you kindly guide a bit what i am doing wrong.

**Comment by gsaslis** [comment]
@BabarAli78 did you verify 2-way connectivity on the network layer between the 2 clients?
