### ISSUE TITLE
SIP registration failed:407 error

### ISSUE THREAD

**Issue by carloscarcamo** [RestComm/restcomm-web-sdk#88]
Hello, I just follow the [Restcomm Client Web SDK Quick Start](http://docs.telestax.com/restcomm-client-web-sdk-quick-start/) tutorial but, when I do `$ nodejs server.js` I got this error in browser console:

```
PrivateJainSipClientConnector:processSipRegisterResponse(): SIP registration failed:407  [object Object]
```

Any idea about this?

Thanks in advance!

**Comment by atsakiridis** [comment]
Hi @carloscarcamo and sorry for the delayed reply. Seems like you 're getting an issue during SIP registration. Which Restcomm server are you targeting? Is it local or somewhere in the WAN? Could you upload the full browser console and also collect full tcpdump in the server side. Rescomm server.log would also help.

Best regards,
Antonis

**Comment by atsakiridis** [comment]
Closing for now, since we didn't hear back from @carloscarcamo. Feel free to reopen if you see this again

**Comment by aduggirala28** [comment]
I have the same error while doing the tutorial at  http://docs.telestax.com/restcomm-client-web-sdk-quick-start/ . The credentials are right as I am able to login with the credentials at cloud.restcomm.com. The credentials in the demo also don't work. 
Thank you. 
Given below are the errors/logs in my browser console.

`This appears to be Chrome
WebRTComm.js:4893 2017-10-07 12:23:40.264 INFO Device::setup(): {"debug":true,"username":"user_name","password":"**********"} 
	[Object.setup (https://localhost:7443/scripts/RestCommWebClient.js:853:13)] 
WebRTComm.js:4893 2017-10-07 12:23:40.265 INFO Device::setup(): registrar has not been provided. Defaulting to wss://cloud.restcomm.com:5063 
	[Object.setup (https://localhost:7443/scripts/RestCommWebClient.js:866:13)] 
WebRTComm.js:4893 2017-10-07 12:23:40.265 INFO Device::setup(): domain has not been provided. Defaulting to cloud.restcomm.com 
	[Object.setup (https://localhost:7443/scripts/RestCommWebClient.js:870:13)] 
WebRTComm.js:4893 2017-10-07 12:23:40.266 INFO WrtcEventListener::WrtcEventListener constructor 
	[new WrtcEventListener (https://localhost:7443/scripts/RestCommWebClient.js:75:11)] 
WebRTComm.js:4893 2017-10-07 12:23:40.277 INFO Device::ready(), assigning ready callback 
	[Object.ready (https://localhost:7443/scripts/RestCommWebClient.js:926:13)] 
WebRTComm.js:4893 2017-10-07 12:23:40.278 INFO Device::error(), assigning error callback 
	[Object.error (https://localhost:7443/scripts/RestCommWebClient.js:1008:13)] 
WebRTComm.js:4893 2017-10-07 12:23:40.278 INFO Device::connect(), assigning connect callback 
	[Object.connect (https://localhost:7443/scripts/RestCommWebClient.js:1032:14)] 
WebRTComm.js:4893 2017-10-07 12:23:40.310 INFO This appears to be Chrome 
	[Object.log (https://localhost:7443/scripts/adapter.js:54:17)] 
WebRTComm.js:4893 2017-10-07 12:23:40.398 INFO 2017-10-07 12:23:40.398 INFO WSMessageChannel:createWebSocket(): the websocket is opened 
	[WebSocket.websocket.onopen (https://localhost:7443/scripts/jain-sip.js:25460:17)]  
	[commonLog (https://localhost:7443/scripts/WebRTComm.js:4893:9)] 
WebRTComm.js:4893 2017-10-07 12:23:40.438 INFO 2017-10-07 12:23:40.438 INFO SIP message sent: REGISTER sip:cloud.restcomm.com SIP/2.0
Call-ID: 1499703820401
CSeq: 1 REGISTER
From: <sip:user_name@cloud.restcomm.com>;tag=1499703820423
To: <sip:user_name@cloud.restcomm.com>
Via: SIP/2.0/WSS nnFF3TVu2mgw.invalid;branch=z9hG4bK-393130-721d064a7539735f3ec53a687c8e14c8;rport
Max-Forwards: 70
User-Agent: TelScale RestComm Web Client 1.0.0 BETA4
Expires: 3600
Allow: INVITE,ACK,CANCEL,BYE,OPTIONS,MESSAGE
Contact: <sip:user_name@nnFF3TVu2mgw.invalid;[object Object]>
Content-Length: 0

 
	[WSMessageChannel.sendMessage (https://localhost:7443/scripts/jain-sip.js:25514:13)]  
	[commonLog (https://localhost:7443/scripts/WebRTComm.js:4893:9)] 
WebRTComm.js:4893 2017-10-07 12:23:40.478 INFO 2017-10-07 12:23:40.478 INFO SIP message received: SIP/2.0 407 Proxy Authentication required
To: <sip:user_name@cloud.restcomm.com>;tag=14982618_8fc6f305_57a5b08a_1f77a809
Via: SIP/2.0/WSS 174.79.191.55:31055;branch=z9hG4bK-393130-721d064a7539735f3ec53a687c8e14c8;rport=31055;received=174.79.191.55
CSeq: 1 REGISTER
Call-ID: 1499703820401
From: <sip:user_name@cloud.restcomm.com>;tag=1499703820423
Server: Restcomm 8.2.0.1549
Proxy-Authenticate: Digest realm="cloud.restcomm.com",nonce="38386136363834632d383833612d343"
Content-Length: 0

 
	[WSMsgParser.parsermessage (https://localhost:7443/scripts/jain-sip.js:20482:13)]  
	[commonLog (https://localhost:7443/scripts/WebRTComm.js:4893:9)] 
WebRTComm.js:4893 2017-10-07 12:23:40.491 INFO 2017-10-07 12:23:40.491 INFO SIP message sent: REGISTER sip:cloud.restcomm.com SIP/2.0
CSeq: 2 REGISTER
User-Agent: TelScale RestComm Web Client 1.0.0 BETA4
Expires: 3600
Allow: INVITE,ACK,CANCEL,BYE,OPTIONS,MESSAGE
Contact: <sip:user_name@nnFF3TVu2mgw.invalid;[object Object]>
Call-ID: 1499703820401
Via: SIP/2.0/WSS nnFF3TVu2mgw.invalid;branch=z9hG4bK-393130-19b09e6e948c8fd482b003af3815f009;rport
From: <sip:manas.sampat@cloud.restcomm.com>;tag=1499703820423
To: <sip:manas.sampat@cloud.restcomm.com>
Max-Forwards: 70
Proxy-Authorization: Digest username="user_name",realm="cloud.restcomm.com",nonce="38386136363834632d383833612d343",response="e5ea997168f2501d8846461ff29f3826",uri="sip:cloud.restcomm.com",algorithm=MD5
Content-Length: 0

 
	[WSMessageChannel.sendMessage (https://localhost:7443/scripts/jain-sip.js:25514:13)]  
	[commonLog (https://localhost:7443/scripts/WebRTComm.js:4893:9)] 
WebRTComm.js:4893 2017-10-07 12:23:48.486 INFO 2017-10-07 12:23:48.486 INFO SIPTransactionStack.prototype.removeDialog(): id=1499703820401:1499703820423:14982618_8fc6f305_57a5b08a_1f77a809 
	[SipStackImpl.SIPTransactionStack.removeDialog (https://localhost:7443/scripts/jain-sip.js:24198:13)]  
	[commonLog (https://localhost:7443/scripts/WebRTComm.js:4893:9)] 
WebRTComm.js:4893 2017-10-07 12:24:12.498 ERROR 2017-10-07 12:24:12.498 ERROR PrivateJainSipClientConnector:processTimeout(): SIP registration timed out, no response from SIP server, Call-Id: 1499703820401. Retrying...  

Stack trace: 
    at commonLog (https://localhost:7443/scripts/WebRTComm.js:4852:10)
    at Object.console.error (https://localhost:7443/scripts/WebRTComm.js:4925:4)
    at PrivateJainSipClientConnector.processTimeout (https://localhost:7443/scripts/WebRTComm.js:1701:12)
    at EventScanner.deliverEvent (https://localhost:7443/scripts/jain-sip.js:29678:25)
    at SipProviderImpl.handleEvent (https://localhost:7443/scripts/jain-sip.js:30896:27)
    at SipProviderImpl.transactionErrorEvent (https://localhost:7443/scripts/jain-sip.js:31439:14)
    at SIPClientTransaction.SIPTransaction.raiseErrorEvent (https://localhost:7443/scripts/jain-sip.js:27602:22)
    at SIPClientTransaction.fireTimeoutTimer (https://localhost:7443/scripts/jain-sip.js:28302:14)
    at SIPClientTransaction.SIPTransaction.fireTimer (https://localhost:7443/scripts/jain-sip.js:27522:18)
    at https://localhost:7443/scripts/jain-sip.js:28481:26 

Stack trace: 
    at commonLog (https://localhost:7443/scripts/WebRTComm.js:4852:10)
    at console.error (https://localhost:7443/scripts/WebRTComm.js:4925:4)
    at commonLog (https://localhost:7443/scripts/WebRTComm.js:4893:9)
    at Object.console.error (https://localhost:7443/scripts/WebRTComm.js:4925:4)
    at PrivateJainSipClientConnector.processTimeout (https://localhost:7443/scripts/WebRTComm.js:1701:12)
    at EventScanner.deliverEvent (https://localhost:7443/scripts/jain-sip.js:29678:25)
    at SipProviderImpl.handleEvent (https://localhost:7443/scripts/jain-sip.js:30896:27)
    at SipProviderImpl.transactionErrorEvent (https://localhost:7443/scripts/jain-sip.js:31439:14)
    at SIPClientTransaction.SIPTransaction.raiseErrorEvent (https://localhost:7443/scripts/jain-sip.js:27602:22)
    at SIPClientTransaction.fireTimeoutTimer (https://localhost:7443/scripts/jain-sip.js:28302:14)
commonLog @ WebRTComm.js:4893
console.error @ WebRTComm.js:4925
commonLog @ WebRTComm.js:4893
console.error @ WebRTComm.js:4925
PrivateJainSipClientConnector.processTimeout @ WebRTComm.js:1701
EventScanner.deliverEvent @ jain-sip.js:29678
SipProviderImpl.handleEvent @ jain-sip.js:30896
SipProviderImpl.transactionErrorEvent @ jain-sip.js:31439
SIPTransaction.raiseErrorEvent @ jain-sip.js:27602
SIPClientTransaction.fireTimeoutTimer @ jain-sip.js:28302
SIPTransaction.fireTimer @ jain-sip.js:27522
(anonymous) @ jain-sip.js:28481
WebRTComm.js:4893 2017-10-07 12:24:12.516 INFO 2017-10-07 12:24:12.514 INFO SIP message sent: REGISTER sip:cloud.restcomm.com SIP/2.0
Call-ID: 1499703852503
CSeq: 1 REGISTER
From: <sip:user_name@cloud.restcomm.com>;tag=1499703852507
To: <sip:user_name@cloud.restcomm.com>
Via: SIP/2.0/WSS nnFF3TVu2mgw.invalid;branch=z9hG4bK-393130-5273da645ef3d648b9d47e98cf45b6a0;rport
Max-Forwards: 70
User-Agent: TelScale RestComm Web Client 1.0.0 BETA4
Expires: 3600
Allow: INVITE,ACK,CANCEL,BYE,OPTIONS,MESSAGE
Contact: <sip:user_name@nnFF3TVu2mgw.invalid;[object Object]>
Content-Length: 0

 
	[WSMessageChannel.sendMessage (https://localhost:7443/scripts/jain-sip.js:25514:13)]  
	[commonLog (https://localhost:7443/scripts/WebRTComm.js:4893:9)] 
WebRTComm.js:4893 2017-10-07 12:24:12.525 WARN 2017-10-07 12:24:12.523 WARN WebRTCommClient:onPrivateClientConnectorOpenWarningEvent():warning:Register Request Timeout 
	[WebRTCommClient.onPrivateClientConnectorOpenWarningEvent (https://localhost:7443/scripts/WebRTComm.js:4764:10)]  
	[commonLog (https://localhost:7443/scripts/WebRTComm.js:4893:9)] 
commonLog @ WebRTComm.js:4893
console.warn @ WebRTComm.js:4919
commonLog @ WebRTComm.js:4893
console.warn @ WebRTComm.js:4919
WebRTCommClient.onPrivateClientConnectorOpenWarningEvent @ WebRTComm.js:4764
PrivateJainSipClientConnector.processTimeout @ WebRTComm.js:1705
EventScanner.deliverEvent @ jain-sip.js:29678
SipProviderImpl.handleEvent @ jain-sip.js:30896
SipProviderImpl.transactionErrorEvent @ jain-sip.js:31439
SIPTransaction.raiseErrorEvent @ jain-sip.js:27602
SIPClientTransaction.fireTimeoutTimer @ jain-sip.js:28302
SIPTransaction.fireTimer @ jain-sip.js:27522
(anonymous) @ jain-sip.js:28481
WebRTComm.js:4893 2017-10-07 12:24:12.570 INFO 2017-10-07 12:24:12.570 INFO SIP message received: SIP/2.0 407 Proxy Authentication required
To: <sip:user_name@cloud.restcomm.com>;tag=05979129_8fc6f305_57a5b08a_e62276e2
Via: SIP/2.0/WSS 174.79.191.55:31055;branch=z9hG4bK-393130-5273da645ef3d648b9d47e98cf45b6a0;rport=31055;received=174.79.191.55
CSeq: 1 REGISTER
Call-ID: 1499703852503
From: <sip:user_name@cloud.restcomm.com>;tag=1499703852507
Server: Restcomm 8.2.0.1549
Proxy-Authenticate: Digest realm="cloud.restcomm.com",nonce="38386538303338322d323333612d343"
Content-Length: 0

 
	[WSMsgParser.parsermessage (https://localhost:7443/scripts/jain-sip.js:20482:13)]  
	[commonLog (https://localhost:7443/scripts/WebRTComm.js:4893:9)] 
WebRTComm.js:4893 2017-10-07 12:24:12.577 ERROR 2017-10-07 12:24:12.577 ERROR PrivateJainSipClientConnector:processSipRegisterResponse(): SIP registration failed:407  [object Object] 

Stack trace: 
    at commonLog (https://localhost:7443/scripts/WebRTComm.js:4852:10)
    at Object.console.error (https://localhost:7443/scripts/WebRTComm.js:4925:4)
    at PrivateJainSipClientConnector.processSipRegisterResponse (https://localhost:7443/scripts/WebRTComm.js:1820:12)
    at PrivateJainSipClientConnector.processResponse (https://localhost:7443/scripts/WebRTComm.js:1645:9)
    at EventScanner.deliverEvent (https://localhost:7443/scripts/jain-sip.js:29660:25)
    at SipProviderImpl.handleEvent (https://localhost:7443/scripts/jain-sip.js:30896:27)
    at DialogFilter.processResponseargu3 (https://localhost:7443/scripts/jain-sip.js:30388:17)
    at DialogFilter.processResponse (https://localhost:7443/scripts/jain-sip.js:30246:14)
    at SIPClientTransaction.nonInviteClientTransaction (https://localhost:7443/scripts/jain-sip.js:28113:32)
    at SIPClientTransaction.processResponseargu3 (https://localhost:7443/scripts/jain-sip.js:28083:18) 

Stack trace: 
    at commonLog (https://localhost:7443/scripts/WebRTComm.js:4852:10)
    at console.error (https://localhost:7443/scripts/WebRTComm.js:4925:4)
    at commonLog (https://localhost:7443/scripts/WebRTComm.js:4893:9)
    at Object.console.error (https://localhost:7443/scripts/WebRTComm.js:4925:4)
    at PrivateJainSipClientConnector.processSipRegisterResponse (https://localhost:7443/scripts/WebRTComm.js:1820:12)
    at PrivateJainSipClientConnector.processResponse (https://localhost:7443/scripts/WebRTComm.js:1645:9)
    at EventScanner.deliverEvent (https://localhost:7443/scripts/jain-sip.js:29660:25)
    at SipProviderImpl.handleEvent (https://localhost:7443/scripts/jain-sip.js:30896:27)
    at DialogFilter.processResponseargu3 (https://localhost:7443/scripts/jain-sip.js:30388:17)
    at DialogFilter.processResponse (https://localhost:7443/scripts/jain-sip.js:30246:14)
commonLog @ WebRTComm.js:4893
console.error @ WebRTComm.js:4925
commonLog @ WebRTComm.js:4893
console.error @ WebRTComm.js:4925
PrivateJainSipClientConnector.processSipRegisterResponse @ WebRTComm.js:1820
PrivateJainSipClientConnector.processResponse @ WebRTComm.js:1645
EventScanner.deliverEvent @ jain-sip.js:29660
SipProviderImpl.handleEvent @ jain-sip.js:30896
DialogFilter.processResponseargu3 @ jain-sip.js:30388
DialogFilter.processResponse @ jain-sip.js:30246
SIPClientTransaction.nonInviteClientTransaction @ jain-sip.js:28113
SIPClientTransaction.processResponseargu3 @ jain-sip.js:28083
SIPClientTransaction.processResponse @ jain-sip.js:28006
SIPClientTransaction.processResponseargu2 @ jain-sip.js:28062
SIPClientTransaction.processResponse @ jain-sip.js:27999
WSMsgParser.processMessage @ jain-sip.js:20515
WSMsgParser.parsermessage @ jain-sip.js:20483
websocket.onmessage @ jain-sip.js:25479
WebRTComm.js:4893 2017-10-07 12:24:12.580 ERROR 2017-10-07 12:24:12.580 ERROR WebRTCommClient:onPrivateClientConnectorOpenErrorEvent():error:undefined 

Stack trace: 
    at commonLog (https://localhost:7443/scripts/WebRTComm.js:4852:10)
    at Object.console.error (https://localhost:7443/scripts/WebRTComm.js:4925:4)
    at WebRTCommClient.onPrivateClientConnectorOpenErrorEvent (https://localhost:7443/scripts/WebRTComm.js:4740:10)
    at PrivateJainSipClientConnector.processSipRegisterResponse (https://localhost:7443/scripts/WebRTComm.js:1822:25)
    at PrivateJainSipClientConnector.processResponse (https://localhost:7443/scripts/WebRTComm.js:1645:9)
    at EventScanner.deliverEvent (https://localhost:7443/scripts/jain-sip.js:29660:25)
    at SipProviderImpl.handleEvent (https://localhost:7443/scripts/jain-sip.js:30896:27)
    at DialogFilter.processResponseargu3 (https://localhost:7443/scripts/jain-sip.js:30388:17)
    at DialogFilter.processResponse (https://localhost:7443/scripts/jain-sip.js:30246:14)
    at SIPClientTransaction.nonInviteClientTransaction (https://localhost:7443/scripts/jain-sip.js:28113:32) 

Stack trace: 
    at commonLog (https://localhost:7443/scripts/WebRTComm.js:4852:10)
    at console.error (https://localhost:7443/scripts/WebRTComm.js:4925:4)
    at commonLog (https://localhost:7443/scripts/WebRTComm.js:4893:9)
    at Object.console.error (https://localhost:7443/scripts/WebRTComm.js:4925:4)
    at WebRTCommClient.onPrivateClientConnectorOpenErrorEvent (https://localhost:7443/scripts/WebRTComm.js:4740:10)
    at PrivateJainSipClientConnector.processSipRegisterResponse (https://localhost:7443/scripts/WebRTComm.js:1822:25)
    at PrivateJainSipClientConnector.processResponse (https://localhost:7443/scripts/WebRTComm.js:1645:9)
    at EventScanner.deliverEvent (https://localhost:7443/scripts/jain-sip.js:29660:25)
    at SipProviderImpl.handleEvent (https://localhost:7443/scripts/jain-sip.js:30896:27)
    at DialogFilter.processResponseargu3 (https://localhost:7443/scripts/jain-sip.js:30388:17)
commonLog @ WebRTComm.js:4893
console.error @ WebRTComm.js:4925
commonLog @ WebRTComm.js:4893
console.error @ WebRTComm.js:4925
WebRTCommClient.onPrivateClientConnectorOpenErrorEvent @ WebRTComm.js:4740
PrivateJainSipClientConnector.processSipRegisterResponse @ WebRTComm.js:1822
PrivateJainSipClientConnector.processResponse @ WebRTComm.js:1645
EventScanner.deliverEvent @ jain-sip.js:29660
SipProviderImpl.handleEvent @ jain-sip.js:30896
DialogFilter.processResponseargu3 @ jain-sip.js:30388
DialogFilter.processResponse @ jain-sip.js:30246
SIPClientTransaction.nonInviteClientTransaction @ jain-sip.js:28113
SIPClientTransaction.processResponseargu3 @ jain-sip.js:28083
SIPClientTransaction.processResponse @ jain-sip.js:28006
SIPClientTransaction.processResponseargu2 @ jain-sip.js:28062
SIPClientTransaction.processResponse @ jain-sip.js:27999
WSMsgParser.processMessage @ jain-sip.js:20515
WSMsgParser.parsermessage @ jain-sip.js:20483
websocket.onmessage @ jain-sip.js:25479
WebRTComm.js:4893 2017-10-07 12:24:12.585 INFO 2017-10-07 12:24:12.585 INFO WrtcEventListener::onWebRTCommClientOpenErrorEventundefined 
	[WrtcEventListener.onWebRTCommClientOpenErrorEvent (https://localhost:7443/scripts/RestCommWebClient.js:98:13)]  
	[commonLog (https://localhost:7443/scripts/WebRTComm.js:4893:9)] 
WebRTComm.js:4893 2017-10-07 12:24:20.494 INFO 2017-10-07 12:24:20.494 INFO SIPTransactionStack.prototype.removeDialog(): id=null 
	[SipStackImpl.SIPTransactionStack.removeDialog (https://localhost:7443/scripts/jain-sip.js:24198:13)]  
	[commonLog (https://localhost:7443/scripts/WebRTComm.js:4893:9)] 
WebRTComm.js:4893 2017-10-07 12:24:20.576 INFO 2017-10-07 12:24:20.576 INFO SIPTransactionStack.prototype.removeDialog(): id=1499703852503:1499703852507:05979129_8fc6f305_57a5b08a_e62276e2 
	[SipStackImpl.SIPTransactionStack.removeDialog (https://localhost:7443/scripts/jain-sip.js:24198:13)]  
	[commonLog (https://localhost:7443/scripts/WebRTComm.js:4893:9)] `

**Comment by atsakiridis** [comment]
@aduggirala28 please avoid commenting in all issues that are similar to yours, as it makes it harder for us to help. Instead, just add any references in your original issue. In any case, please check my response to #108 and we can take it from there

**Comment by aduggirala28** [comment]
Okay, thanks. Duly noted !
